### ISSUE TITLE
Latest version doesn't work with current stable build of chrome

### ISSUE THREAD

**Issue by Skawtnyc** [jtmcgrath/harmony#2]
Chrome Version 69.0.3497.100 (Official Build) (64-bit)

The extension installs but the features of the extension do not function.

**Comment by jtmcgrath** [comment]
Huh, didn't get a notification for this... Are you still experiencing problems @Skawtnyc? I've not encountered anything, aside from occasional changes to Discord UI meaning that the styling sometimes breaks!

**Comment by Skawtnyc** [comment]
Sorry, I haven't used the extension for a while now. I'm currently using Stylus and CSS code to adjust Discord the way I want.
